FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD NotepadPro.jar /opt/NotepadPro/
EXPOSE 8080
WORKDIR /opt/NotepadPro/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "NotepadPro.jar"]
