PostgreSQL:
  image: postgres:latest
  ports:
    - "5432:5432"
  environment:
    - DB_USER=postgres
    - DB_PASS=docker
    - DB_NAME=notepad
#    - DB_TEMPLATE=
#
#    - DB_EXTENSION=
#
#    - REPLICATION_MODE=
#    - REPLICATION_USER=
#    - REPLICATION_PASS=
#    - REPLICATION_SSLMODE=
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
NotepadPro:
  image:
